#!/bin/bash -x

[ -n "$vdpalog" ] || {
sudo sw/dpdk/build/examples/dpdk-vdpa -a 0000:00:00.0 --log-level=.,8 -- --client --iface /tmp/vf- ;
exit 0;
}

loginfo dpdk-vdpa $pfslot $vfslot
# background run
tail -f /dev/null | \
sw/dpdk/build/examples/dpdk-vdpa -a 0000:00:00.0 --log-level=.,8 -- --client --iface /tmp/vf- \
 >> $vdpalog 2>&1 &

